### ISSUE TITLE
缩放QML窗口右上角有系统的关闭按钮

### ISSUE THREAD

**Issue by lowbees** [qtdevs/FramelessHelper#2]
缩放qml窗口时，右上角有系统的关闭按钮，原因是加了WS_SYSMENU这个style

**Comment by ericzh86** [comment]
这个主要是 QML 后台渲染设备获取了系统客户区域的问题，暂时还没时间看。

**Comment by xuelongqy** [comment]
Qml状态栏是黑色的，左边也有黑色的边

**Comment by ericzh86** [comment]
QML 这个无解，是 QML 底层渲染机制的 bug，目前没办法。

**Comment by ericzh86** [comment]
经过验证，Windows 10 + Qt 5.9.6 + Visual Studio 2015 没有再出现此问题，等待其他人验证后会关闭这个问题。
