### ISSUE TITLE
窗口大小和位置的计算有问题

### ISSUE THREAD

**Issue by wangwenx190** [qtdevs/FramelessHelper#4]
使用 Qt 5.11.1 只有无边框效果，标题栏并不能正常工作，窗口也无法自由缩放，Qt 5.9.6 则正常。

**Comment by wangwenx190** [comment]
今天我用 Qt 5.12.0 Alpha 试了试，还是有同样的问题，只有无边框效果，但标题栏并不能正常工作，不能拖动，也不能双击最大化，窗口也无法自由缩放。

这个项目计算窗口大小和位置时也有点问题，如果重复最大化->还原->最小化->还原，会发现窗口位置会逐渐下移，而且窗口位置经常会莫名其妙的自行移动。

**Comment by wangwenx190** [comment]
刚刚用 5.11.2 正式版试了下，还是有同样的问题，看来您的项目并不能兼容版本高于 5.9.6 的Qt。

**Comment by wangwenx190** [comment]
现在已确认，在 Qt 5.11.1，5.11.2 和 5.12.0 Alpha 中标题栏不能正常工作是 Qt 自身的 bug，请见 https://bugreports.qt.io/browse/QTBUG-70873 ，目前 Qt 官方已修复，在未来的 Qt 5.11.3 和 5.12.0 正式版中会恢复正常。但不论哪个版本，窗口大小和位置的计算都有些问题。

**Comment by wangwenx190** [comment]
今天用 5.12.0 正式版试了下，无法拖动的 bug 官方已经修复了，但窗口最大化后再恢复正常大小，窗口的位置会比原来上移一些，挺明显的。暂未发现其他问题。之前提到的重复最大化->还原->最小化->还原，窗口逐渐下移的问题也没有了。

**Comment by zhoujun59761** [comment]
Windows 10 + Visual Studio 2017 + Qt 5.12.0，暂时没有发现有问题。现在这个问题还存在吗？

**Comment by wangwenx190** [comment]
暂未发现，可能之前所有的问题都是Qt自身的bug导致的。有问题我再提issue。
