### ISSUE TITLE
去除对widgets模块的强制依赖

### ISSUE THREAD

**Issue by wangwenx190** [qtdevs/FramelessHelper#5]
单纯的Qt Quick应用是不依赖widgets模块的，而此项目的.pro文件和部分.cpp文件里都不加判断的依赖了widgets模块的相关文件。能不能加一个配置文件，或者写两个.pro/.pri文件，不要强制依赖widgets模块，比比如我自己的项目就是纯Qt Quick项目，根本不依赖widgets模块，但用了这个项目之后，就要多带一个不小的dll，很不方便。

**Comment by lowbees** [comment]
只用FramelessHelper就可以了，里面有个pri可以包含

**Comment by wangwenx190** [comment]
@lowbees
我就是这样做的，不行，有些cpp文件还是头文件用到了widgets的头文件，会报错，你亲自编译一次试试就知道了

**Comment by lowbees** [comment]
@wangwenx190 
去掉FramelessHelper这几个头文件跟源文件就可以了，这个项目是QWidget跟QML都可以用的

**Comment by wangwenx190** [comment]
好的
