### ISSUE TITLE
 Maximize window issue. Windows 10, Qt 5.13.1, MSVC 2017

### ISSUE THREAD

**Issue by JasonLi777** [qtdevs/FramelessHelper#9]
Maximize window fail when set windows scale to 150%.
![Capture](https://user-images.githubusercontent.com/25840650/66874139-d1b0b680-f006-11e9-8f71-46c74cf728c2.JPG)
![Capture2](https://user-images.githubusercontent.com/25840650/66874140-d1b0b680-f006-11e9-94dc-2c573ffbdeb4.JPG)

**Comment by ericzh86** [comment]
fixed in the latest commit.
